### ISSUE TITLE
Hi Xintao, Can you give me your result that you apply your approach on the dataset set5, set14 and BSD 100, I want to quote your paper and results on these dataset in my paper, ok?

### ISSUE THREAD

**Issue by chensongkui** [xinntao/SFTGAN#8]
Hi Xintao,
Can you give me your result that you apply your approach on the dataset set5, set14 and BSD 100, I want to quote your paper and results on these dataset in my paper, ok?

**Comment by xinntao** [comment]
Hi @chensongkui,

In the original paper, the model aims for **outdoor scenes**. And the results for set5, set14, and BSD100 may not be optimal, since the segmentation results for them is not good enough. 

If you want to compare with them, you can run the pytorch test codes in this repo. I think it's not so complicated.

**Comment by chensongkui** [comment]
OK, thank you!
